1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return [
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]
]

In [1]:
import numpy as np

def solve(a,b,c):
    d=np.full((a,b),c)
    return d

In [2]:
solve(3,3,5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

2.	Create a method that takes n numpy arrays of same dimensions sums them and return the answer.

In [3]:
def add_aray(a,b):
    d=np.add(a,b)
    return d

In [4]:
a = np.array([10,20,30])
b = np.array([40,50,60])

In [5]:
add_aray(a,b)

array([50, 70, 90])

3.	Given a 2 D Array of N X M Dimesion, Write a function that accepts this array as well as two numbers N and M. The method should return the top-left N X M sub matrix e.g:
   [
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
   ]
   
   top_left_sub_matrix(matrix, 2, 2) -> should return :
   [
       [1, 2]
       [4, 5]
   ]

In [6]:
def top_left_sub_matrix(matrix,a,b):
    print(matrix[:a, :b])

In [7]:
matrix = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
top_left_sub_matrix(matrix,2,2)

[[1 2]
 [4 5]]


4.	Given a 2 D Array of N X M Dimesion, Write a function that accepts this array as well as two numbers N and M   The method should return the bottom-right N X M sub matrix e.g:
   [
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
   ]
   
   sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
   [
       [5, 6]
       [8, 9]
   ]


In [9]:
def bottom_right_sub_matrix(matrix,a,b):
    print(matrix[a:, b:])

bottom_right_sub_matrix(matrix,1,1)

[[5 6]
 [8 9]]


5.	Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values:
    [1, 1, 1]
   solution(arr) -> should return :
   {'mean': 1.0, 'std_dev': 0.0}


In [10]:
def computation(a):
    b = np.mean(a)
    c = np.std(a)
    d = np.median(a)
    dict_d = {"mean":b, "std":c, "median":d}
    return dict_d

In [11]:
a = np.array([1,1,1])

In [12]:
computation(a)

{'mean': 1.0, 'std': 0.0, 'median': 1.0}